### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by miguelmota** [miguelmota/shredbeat#1]
PHASE 1
- [ ] player controls (scrobbler)
- [ ] playlist view
- [ ] song info
- [x] quit button
- [ ] move and read db from `~/.shredbeat`
- [ ] config options (min/max volume, shredometer tweaking, playback range)
- [ ] audio scrobbler
- [ ] options revert defaults button

PHASE 2
- [ ] tune in to other shredbeaters
- [ ] achievement sounds (shredmaster, shredtacular, shredfrenzy, shredrage, shredgod)
- [ ] theming options
